apiVersion: v1
kind: Pod
metadata:
  name: drop-cap-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sleep", "3600"]
    securityContext:
      capabilities:
        drop:
          - ALL
